[features]
seeds = false

[programs.devnet]
breed_program = "CikztTpnE9wiNzafzTCSzE4tXKFi5iHcGKzBhpNTiP7p"
[programs.localnet]
breed_program = "CikztTpnE9wiNzafzTCSzE4tXKFi5iHcGKzBhpNTiP7p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/anchor.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.devnet.solana.com"

# Authority
[[test.validator.clone]]
address = "7CY9dKWDQimK43RkGXyT7BUpgvUGduSbCRt4RNpv2L8w"

# User address
[[test.validator.clone]]
address = "9BeNtJPhQfV7iRGvgNGMC7Q8hBaiESE5YKQaHQTeiWRr"
# Mint A
[[test.validator.clone]]
address = "4kZVPqN3b2CFUniF8bBdex32ziQ3FxbxhNYT3teV7Jkx"
# Mint A metadata
[[test.validator.clone]]
address = "5e22jre9DQYKUZctASDaskucmahgmJJ8JtkubpYDZiqX"
# User Mint A ATA
[[test.validator.clone]]
address = "Dip3H8tgZGnHqPSkMXiWrX2i64ZQRed63CaBo3FBKF4M"
# Mint B
[[test.validator.clone]]
address = "2Z8esbcvecdEDXp6Py3HW3th9CAUJtTW5Df3Lz1m6qJC"
# Mint B metadata
[[test.validator.clone]]
address = "6mdz34FCJ3tHhmwcwTpreT9D3ULeDgDAnSoTKNrBJvxm"
# User Mint B ATA
[[test.validator.clone]]
address = "CdpebUieyDUgU6AEyk3dpzN7GGPdueoNMR6nYa5Eqtaf"
# Fee token address
[[test.validator.clone]]
address = "NEpinL3xGXUpDeLdiJmVAoMGHXVF6BjsPHV6HRtNZDh"
# User fee token ATA
[[test.validator.clone]]
address = "5qqv2Zs8AjEesRTwV8E2oMsoMjzkCEFu8mr9nN2dCZ6m"

# Token program
[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
# Associated token program
[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
# Token metadata program
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"




# NFTs

# holder wallet
[[test.validator.clone]]
address = "ViVDtpVYKdhRRH9FTKsh6reJB9xXUqpX1233BSDZWRQ"

# program idl
[[test.validator.clone]]
address = "DTddp5dRUfTYrrPjkdSxZqg1TkyEprbYhJpmNpLd8tSf"

# ViV wallet feeToken
[[test.validator.clone]]
address = "6N4FqZM23cyWCNN3AcUFF9CpRuY1SYMqMRbfHTtB83M1"

# ViV wallet feeToken ATA
[[test.validator.clone]]
address = "DmiTsvSV7aFGEmSRMYs9V857wfKmoxE9wpffz7Fi4WCc"

# nft mint
[[test.validator.clone]]
address = "41jKeBpGH6Ur46r9fMc8JjyAbXitTB5BAdo7SGF82RoY"

# nft holder account
[[test.validator.clone]]
address = "7U1G1DJAm51evMyN6RM7SyRAkrfGEC7B2CBc4CYnQthE"


# nft metadata
[[test.validator.clone]]
address = "4cJ8hMuocWqJ8gmiviHEduv5X9EmagFPk5Uba16b4Zvh"



# nft 2 mint
[[test.validator.clone]]
address = "FbgRi6cUD581knBjtovPYajdRp8fEqVDgJLVhK3V8372"

# nft 2 holder account
[[test.validator.clone]]
address = "Ax6gAkkBKWcKSRU2vitdPwiw6hFK3xL9wZ6GRCAuYPhA"


# nft 2 metadata
[[test.validator.clone]]
address = "9umFMEbzrXjPqkcbUCcedzWosVzuaGz8Pm2ugeFeA4kM"


